name = "portfolio optimizer"
description = "A simple application that loads a csv and displays a table of its contents."
packages = [ "pandas", "numpy", "scipy"]

[files]
"https://quanzoo.github.io/PortfolioOptimizer/portopt.py" = "./portopt.py"